version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 77M
        reservations:
          cpus: '0.01'
          memory: 30M

  seo:
    image: seohyeongwon/8trider.github.io:1.1.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=asdf.com
      - VIRTUAL_PORT=80


  aain:
    image: aaingyunii/aaingyunii.github.io
    expose:
      - ""
    environment:
      - VIRTUAL_HOST=qwer.example

